name: "GitHub Pages Web app deploy"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.4"
          channel: "stable"
      - run: |
          flutter build web --base-href /${{ github.event.repository.name }}/
          git config --global user.email "tinytengu@yandex.ru"
          git config --global user.name "tinytengu"
          git push origin :gh-pages && git subtree push --prefix dist origin gh-pages
          git subtree push --prefix build/web origin gh-pages
          rm -rf build
